const subjectList = [
  {
    "Name": "Astronomy",
    "Abbreviation": "ASTR"
  },
  {
    "Name": "Computer Science",
    "Abbreviation": "COMP"
  },
  {
    "Name": "English",
    "Abbreviation": "ENGL"
  },
  {
    "Name": "Family Social Sciences",
    "Abbreviation": "FMLY"
  }
];

const classList = [
  {
    "CRN": 1535,
    "Subject": "ASTR",
    "Course": 1810,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Life in the Universe",
    "Days": "MTWR",
    "Time": "2:15 PM - 3:30 PM",
    "Cap": 170,
    "Act": 0,
    "Rem": 170,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Michelle M. Boyce",
    "Date": "05/08-06/15",
    "Location": "TBA",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 17162,
    "Subject": "ASTR",
    "Course": 2000,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Foundations of Astrophysics",
    "Days": "MWF",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 50,
    "Act": 27,
    "Rem": 23,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Michelle M. Boyce",
    "Date": "09/07-12/12",
    "Location": "406 Tier",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 18574,
    "Subject": "ASTR",
    "Course": 3070,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Observational Astronomy Project",
    "Days": "TR",
    "Time": "7:00 PM - 9:45 PM",
    "Cap": 9,
    "Act": 6,
    "Rem": 3,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Danielle M. Pahud",
    "Date": "09/07-12/12",
    "Location": "382 University College",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 20369,
    "Subject": "ASTR",
    "Course": 3180,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Stars",
    "Days": "TR",
    "Time": "1:00 PM - 2:15 PM",
    "Cap": 20,
    "Act": 13,
    "Rem": 7,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Erica L. Franzmann",
    "Date": "09/07-12/12",
    "Location": "419 Machray Hall",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 50102,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 1",
    "Days": "MWF",
    "Time": "12:30 PM - 1:20 PM",
    "Cap": 150,
    "Act": 105,
    "Rem": 45,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09 - 04/12",
    "Location": "221 Wallace",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": "62018;50110;50116;50111;50112;62019"
  },
  {
    "CRN": 51234,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 1",
    "Days": "TR",
    "Time": "12:30 PM - 1:20 PM",
    "Cap": 150,
    "Act": 105,
    "Rem": 45,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "221 Wallace",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": "51236;51237;51238;51239;51240;51241"
  },
  {
    "CRN": 52242,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 1",
    "Days": "TR",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 150,
    "Act": 93,
    "Rem": 57,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Michael Arnold",
    "Date": "01/09 = 04/12",
    "Location": "221 Wallace",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": "62020;50119;50113;50108;50114;62021"
  },
  {
    "CRN": 51235,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 1",
    "Days": "MWF",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 150,
    "Act": 150,
    "Rem": 0,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Michael Arnold",
    "Date": "05/08-06/15",
    "Location": "221 Wallace",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": "51242;51243;51244;51245;51246;51247"
  },
  {
    "CRN": 62018,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51236,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 50110,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B02",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51237,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B02",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 50116,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B03",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 28,
    "Act": 18,
    "Rem": 10,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51238,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B03",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 28,
    "Act": 18,
    "Rem": 10,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 50111,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B04",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 28,
    "Act": 23,
    "Rem": 5,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51239,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B04",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 28,
    "Act": 23,
    "Rem": 5,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 50112,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B05",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "2:30 PM - 3:20 PM",
    "Cap": 28,
    "Act": 20,
    "Rem": 8,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51240,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B05",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "2:30 PM - 3:20 PM",
    "Cap": 28,
    "Act": 20,
    "Rem": 8,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 62019,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B06",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "3:30 PM - 4:20 PM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50102
  },
  {
    "CRN": 51241,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B06",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "W",
    "Time": "3:30 PM - 4:20 PM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51234
  },
  {
    "CRN": 62020,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B07",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 12,
    "Rem": 16,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "113 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51242,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B07",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 12,
    "Rem": 16,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "113 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 50119,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B08",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51243,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B08",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 28,
    "Act": 16,
    "Rem": 12,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 50113,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B09",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 28,
    "Act": 15,
    "Rem": 13,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51244,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B09",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 28,
    "Act": 15,
    "Rem": 13,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 50108,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B10",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 28,
    "Act": 22,
    "Rem": 6,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51245,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B10",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 28,
    "Act": 22,
    "Rem": 6,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 50114,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B11",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "2:30 PM - 3:20 PM",
    "Cap": 28,
    "Act": 15,
    "Rem": 13,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51246,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B11",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "2:30 PM - 3:20 PM",
    "Cap": 28,
    "Act": 15,
    "Rem": 13,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "108 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 62021,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B12",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "3:30 PM - 4:20 PM",
    "Cap": 28,
    "Act": 9,
    "Rem": 19,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "01/09-04-12",
    "Location": "115 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 52242
  },
  {
    "CRN": 51247,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "B12",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 1",
    "Days": "F",
    "Time": "3:30 PM - 4:20 PM",
    "Cap": 28,
    "Act": 9,
    "Rem": 19,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Patrick M. Dubois",
    "Date": "05/08-06/15",
    "Location": "115 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 51242
  },
  {
    "CRN": 50702,
    "Subject": "COMP",
    "Course": 1010,
    "Section": "D01",
    "Campus": "DE",
    "Credits": 3,
    "Title": "Introductory Computer Science 1",
    "Days": "TBA",
    "Time": "N/A",
    "Cap": 500,
    "Act": 168,
    "Rem": 332,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Reyhaneh Ababzadeh",
    "Date": "01/09 - 04/12",
    "Location": "Distance And On-Line Education",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 51716,
    "Subject": "COMP",
    "Course": 1012,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Programming for Scientists and Engineers",
    "Days": "TR",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 150,
    "Act": 138,
    "Rem": 12,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Japjeet Singh",
    "Date": "01/09-04/12",
    "Location": "100 Fletcher Argue",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 52825
  },
  {
    "CRN": 51874,
    "Subject": "COMP",
    "Course": 1012,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Programming for Scientists and Engineers",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 150,
    "Act": 133,
    "Rem": 17,
    "WLCap": 1998,
    "WLAct": 0,
    "WLRem": 1998,
    "Instructor": "Meng C. Lau",
    "Date": "01/09-04/12",
    "Location": "223 Wallace",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 52875
  },
  {
    "CRN": 52825,
    "Subject": "COMP",
    "Course": 1012,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Computer Programming for Scientists and Engineers",
    "Days": "W",
    "Time": "8:30:00 AM - 9:20 AM",
    "Cap": 30,
    "Act": 14,
    "Rem": 16,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "TBA",
    "Date": "01/09-04/12",
    "Location": "115 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 51716
  },
  {
    "CRN": 52875,
    "Subject": "COMP",
    "Course": 1012,
    "Section": "B02",
    "Campus": "M",
    "Credits": 0,
    "Title": "Computer Programming for Scientists and Engineers",
    "Days": "W",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 30,
    "Act": 27,
    "Rem": 3,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "TBA",
    "Date": "01/09-04/12",
    "Location": "115 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 51874
  },
  {
    "CRN": 58057,
    "Subject": "COMP",
    "Course": 1020,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 2",
    "Days": "MWF",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 110,
    "Act": 94,
    "Rem": 16,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Josiane Kroll",
    "Date": "01/09-04/12",
    "Location": "207 Buller",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50123
  },
  {
    "CRN": 50121,
    "Subject": "COMP",
    "Course": 1020,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 2",
    "Days": "TR",
    "Time": "10:00:00 AM - 11:15 AM",
    "Cap": 110,
    "Act": 91,
    "Rem": 19,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "John P. Braico",
    "Date": "01/09-04/12",
    "Location": "110 Eitc E2",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 50122,
    "Subject": "COMP",
    "Course": 1020,
    "Section": "A03",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introductory Computer Science 2",
    "Days": "MWF",
    "Time": "8:30 AM - 9:20 AM",
    "Cap": 109,
    "Act": 84,
    "Rem": 25,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Rogerio de Leon Pereira",
    "Date": "01/09-04/12",
    "Location": "110 Eitc E2",
    "Attribute": "Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50128
  },
  {
    "CRN": 50123,
    "Subject": "COMP",
    "Course": 1020,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 2",
    "Days": "W",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 26,
    "Rem": 2,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "John P. Braico",
    "Date": "01/09-04/12",
    "Location": "111 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 58057
  },
  {
    "CRN": 50128,
    "Subject": "COMP",
    "Course": 1020,
    "Section": "B02",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introductory Computer Science 2",
    "Days": "W",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 28,
    "Act": 19,
    "Rem": 9,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "John P. Braico",
    "Date": "01/09-04/12",
    "Location": "115 Machray Hall",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science and Recommended Intro Courses",
    "Labs": 50122
  },
  {
    "CRN": 60163,
    "Subject": "COMP",
    "Course": 2080,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Analysis of Algorithms",
    "Days": "TR",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 110,
    "Act": 90,
    "Rem": 20,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Timothy Zapp",
    "Date": "01/09-04/12",
    "Location": "207 Buller",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 58045,
    "Subject": "COMP",
    "Course": 2080,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Analysis of Algorithms",
    "Days": "TR",
    "Time": "4:00 PM - 5:15 PM",
    "Cap": 110,
    "Act": 103,
    "Rem": 7,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jennifer Vaughan",
    "Date": "01/09-04/12",
    "Location": "201 Armes",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 50140,
    "Subject": "COMP",
    "Course": 2140,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Data Structures and Algorithms",
    "Days": "MWF",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 96,
    "Act": 89,
    "Rem": 7,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Phil Pitura",
    "Date": "01/09-04/12",
    "Location": "118 St. John's College",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 51249
  },
  {
    "CRN": 51248,
    "Subject": "COMP",
    "Course": 2140,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Data Structures and Algorithms",
    "Days": "MWF",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 96,
    "Act": 89,
    "Rem": 7,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Phil Pitura",
    "Date": "05/08-06/15",
    "Location": "118 St. John's College",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 52478
  },
  {
    "CRN": 51249,
    "Subject": "COMP",
    "Course": 2140,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Data Structures and Algorithms",
    "Days": "T",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 24,
    "Act": 23,
    "Rem": 1,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Phil Pitura",
    "Date": "05/08-06/15",
    "Location": "450 Eitc E2",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 50140
  },
  {
    "CRN": 52478,
    "Subject": "COMP",
    "Course": 2140,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Data Structures and Algorithms",
    "Days": "T",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 24,
    "Act": 23,
    "Rem": 1,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Phil Pitura",
    "Date": "1/31, 2/14, 3/7, 3/21, 4/4",
    "Location": "450 Eitc E2",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 51248
  },
  {
    "CRN": 59659,
    "Subject": "COMP",
    "Course": 2150,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Object Orientation",
    "Days": "TR",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 110,
    "Act": 93,
    "Rem": 17,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Franklin Bristow",
    "Date": "01/09-04/12",
    "Location": "205 Armes",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 52553,
    "Subject": "COMP",
    "Course": 2150,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Object Orientation",
    "Days": "MWF",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 110,
    "Act": 107,
    "Rem": 3,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Olivier Tremblay-Savard",
    "Date": "01/09-04/12",
    "Location": "118 St. John's College",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 51561,
    "Subject": "COMP",
    "Course": 2160,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Programming Practices",
    "Days": "MWF",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 110,
    "Act": 98,
    "Rem": 12,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Saulo Q. dos Santos",
    "Date": "01/09-04/12",
    "Location": "105 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 51562
  },
  {
    "CRN": 51562,
    "Subject": "COMP",
    "Course": 2160,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Programming Practices",
    "Days": "W",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 24,
    "Act": 21,
    "Rem": 3,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Saulo Q. dos Santos",
    "Date": "1/25, 2/08, 3/01, 3/15, 3/29",
    "Location": "420 Eitc E2",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 51561
  },
  {
    "CRN": 50152,
    "Subject": "COMP",
    "Course": 2280,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Computer Systems",
    "Days": "TR",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 108,
    "Act": 84,
    "Rem": 24,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Michael Zapp",
    "Date": "01/09-04/12",
    "Location": "200 Fletcher Argue",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 50153
  },
  {
    "CRN": 60164,
    "Subject": "COMP",
    "Course": 2280,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Computer Systems",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 108,
    "Act": 98,
    "Rem": 10,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Emanuel Wiens",
    "Date": "01/09-4/12",
    "Location": "118 St. John's College",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": 50154
  },
  {
    "CRN": 50153,
    "Subject": "COMP",
    "Course": 2280,
    "Section": "B01",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introduction to Computer Systems",
    "Days": "W",
    "Time": "8:30 AM - 9:45 AM",
    "Cap": 24,
    "Act": 22,
    "Rem": 2,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Michael Zapp",
    "Date": "01/09-04/12",
    "Location": "420 Eitc E2",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 50152
  },
  {
    "CRN": 50154,
    "Subject": "COMP",
    "Course": 2280,
    "Section": "B02",
    "Campus": "M",
    "Credits": 0,
    "Title": "Introduction to Computer Systems",
    "Days": "W",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 24,
    "Act": 19,
    "Rem": 5,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Michael Zapp",
    "Date": "01/09-04/12",
    "Location": "420 Eitc E2",
    "Attribute": "Lab Fee Category I and Science Requirement for BA and Science",
    "Labs": 60164
  },
  {
    "CRN": 14072,
    "Subject": "COMP",
    "Course": 3020,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human-Computer Interaction 1",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 80,
    "Act": 79,
    "Rem": 1,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Anata Chowdhury",
    "Date": "09/07-12/12",
    "Location": "350 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10186,
    "Subject": "COMP",
    "Course": 3020,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human-Computer Interaction 1",
    "Days": "MWF",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 80,
    "Act": 76,
    "Rem": 4,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Patrick M. Dubois",
    "Date": "09/07-12/12",
    "Location": "235 Isbister",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10190,
    "Subject": "COMP",
    "Course": 3190,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Artificial Intelligence",
    "Days": "MWF",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 90,
    "Act": 86,
    "Rem": 4,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "John E. Anderson",
    "Date": "09/07-12/12",
    "Location": "201 Armes",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 13091,
    "Subject": "COMP",
    "Course": 3370,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Organization",
    "Days": "TR",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 100,
    "Act": 84,
    "Rem": 16,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Rasit Eskicioglu",
    "Date": "09/07-12/12",
    "Location": "122 Drake Centre",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10197,
    "Subject": "COMP",
    "Course": 3380,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Databases Concepts and Usage",
    "Days": "TR",
    "Time": "8:30 AM - 9:45 AM",
    "Cap": 80,
    "Act": 75,
    "Rem": 5,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Patrick M. Dubois",
    "Date": "09/07-12/12",
    "Location": "235 Isbister",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 15304,
    "Subject": "COMP",
    "Course": 3380,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Databases Concepts and Usage",
    "Days": "TR",
    "Time": "4:00 PM - 5:15 PM",
    "Cap": 80,
    "Act": 76,
    "Rem": 4,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Robert W. Guderian",
    "Date": "09/07-12/12",
    "Location": "160 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 51250,
    "Subject": "COMP",
    "Course": 3490,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Graphics 1",
    "Days": "MWF",
    "Time": "12:30 PM - 1:20 PM",
    "Cap": 90,
    "Act": 90,
    "Rem": 0,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jennifer Vaughan",
    "Date": "05/08-06/15",
    "Location": "343 Drake Centre",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10209,
    "Subject": "COMP",
    "Course": 3490,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Graphics 1",
    "Days": "MWF",
    "Time": "12:30 PM - 1:20 PM",
    "Cap": 90,
    "Act": 79,
    "Rem": 11,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jennifer Vaughan",
    "Date": "09/07-12/12",
    "Location": "343 Drake Centre",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 51250,
    "Subject": "COMP",
    "Course": 3490,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Graphics 1",
    "Days": "TR",
    "Time": "2:30 PM - 3:20 PM",
    "Cap": 59,
    "Act": 90,
    "Rem": 0,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jennifer Vaughan",
    "Date": "05/08-06/15",
    "Location": "343 Drake Centre",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10210,
    "Subject": "COMP",
    "Course": 4050,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Project Management",
    "Days": "TR",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 51,
    "Act": 51,
    "Rem": 0,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Franklin Bristow",
    "Date": "09/07-12/12",
    "Location": "229 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 10213,
    "Subject": "COMP",
    "Course": 4140,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Cryptography and Cryptosystems",
    "Days": "MWF",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 50,
    "Act": 48,
    "Rem": 2,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Pakching B. Li",
    "Date": "09/07-12/12",
    "Location": "108 Human Ecology",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 13093,
    "Subject": "COMP",
    "Course": 4300,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computer Networks",
    "Days": "MWF",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 50,
    "Act": 49,
    "Rem": 1,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Sara Rouhani",
    "Date": "09/07-12/12",
    "Location": "108 Human Ecology",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 22386,
    "Subject": "COMP",
    "Course": 4360,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Machine Learning",
    "Days": "TR",
    "Time": "4:00 PM - 5:15 PM",
    "Cap": 50,
    "Act": 39,
    "Rem": 11,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Lorenzo Livi",
    "Date": "09/07-12/12",
    "Location": "406 Tier",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 11128,
    "Subject": "COMP",
    "Course": 4510,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Parallel Computation",
    "Days": "MWF",
    "Time": "10:30 AM - 11:20 AM",
    "Cap": 50,
    "Act": 28,
    "Rem": 22,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Parimala Thulasiraman",
    "Date": "09/07-12/12",
    "Location": "108 Human Ecology",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 51251,
    "Subject": "COMP",
    "Course": 7570,
    "Section": "T15",
    "Campus": "M",
    "Credits": 3,
    "Title": "Blockchain Systems and Decentralized Applications",
    "Days": "MW",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 17,
    "Act": 17,
    "Rem": 0,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Sara Rouhani",
    "Date": "05/08-06/15",
    "Location": "164 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 22036,
    "Subject": "COMP",
    "Course": 7570,
    "Section": "T15",
    "Campus": "M",
    "Credits": 3,
    "Title": "Blockchain Systems and Decentralized Applications",
    "Days": "MW",
    "Time": "2:30 PM - 3:45 PM",
    "Cap": 17,
    "Act": 16,
    "Rem": 1,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Sara Rouhani",
    "Date": "09/07-12/12",
    "Location": "164 Eitc E2",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 21256,
    "Subject": "COMP",
    "Course": 7922,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Computational Geometry",
    "Days": "MW",
    "Time": "9:30 AM - 10:45 AM",
    "Cap": 15,
    "Act": 15,
    "Rem": 0,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Stephane J. Durocher",
    "Date": "09/07-12/12",
    "Location": "316 Machray Hall",
    "Attribute": "Science Requirement for BA and Science",
    "Labs": ""
  },
  {
    "CRN": 51681,
    "Subject": "ENGL",
    "Course": 930,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "English Composition",
    "Days": "MWF",
    "Time": "9:30 AM - 10:20 AM",
    "Cap": 28,
    "Act": 19,
    "Rem": 9,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jenifer N. Mohammed",
    "Date": "01/09-04/12",
    "Location": "318 St. Paul's College",
    "Attribute": "Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 50626,
    "Subject": "ENGL",
    "Course": 930,
    "Section": "D01",
    "Campus": "DE",
    "Credits": 3,
    "Title": "English Composition",
    "Days": "TBA",
    "Time": "N/A",
    "Cap": 40,
    "Act": 33,
    "Rem": 7,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Lisa Dorcich",
    "Date": "01/09-04/12",
    "Location": "Distance And On-Line Education",
    "Attribute": "Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 52356,
    "Subject": "ENGL",
    "Course": 930,
    "Section": "G07",
    "Campus": "M",
    "Credits": 3,
    "Title": "English Composition",
    "Days": "TBA",
    "Time": "N/A",
    "Cap": 0,
    "Act": 0,
    "Rem": 0,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "TBA",
    "Date": "01/09-04/12",
    "Location": "N/A",
    "Attribute": "Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 50075,
    "Subject": "ENGL",
    "Course": 1340,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Literary Analysis",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 40,
    "Act": 35,
    "Rem": 5,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Erin M. Keating",
    "Date": "01/09-04/12",
    "Location": "301 Tier",
    "Attribute": "Humanities and Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 59633,
    "Subject": "ENGL",
    "Course": 1340,
    "Section": "A02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Literary Analysis",
    "Days": "TR",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 40,
    "Act": 34,
    "Rem": 6,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Erin Weinberg",
    "Date": "01/09-04/12",
    "Location": "401 Tier",
    "Attribute": "Humanities and Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 62854,
    "Subject": "ENGL",
    "Course": 1340,
    "Section": "A03",
    "Campus": "M",
    "Credits": 3,
    "Title": "Introduction to Literary Analysis",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 50,
    "Act": 48,
    "Rem": 2,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Jamie Paris",
    "Date": "01/09-04/12",
    "Location": "306 Buller",
    "Attribute": "Humanities and Recommended Intro Courses and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 21234,
    "Subject": "ENGL",
    "Course": 2130,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Literature of the Romantic Period (Part A & B)",
    "Days": "MWF",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 45,
    "Act": 45,
    "Rem": 0,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Michelle R. Faubert",
    "Date": "05/08-06/15",
    "Location": "Tier 406",
    "Attribute": "Humanities and English:Lit Prior to 20th Cent and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 22360,
    "Subject": "ENGL",
    "Course": 2130,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Literature of the Romantic Period (Part A & B)",
    "Days": "MWF",
    "Time": "1:30 PM - 2:20 PM",
    "Cap": 45,
    "Act": 41,
    "Rem": 4,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Michelle R. Faubert",
    "Date": "09/07-12/12, 01/09-04/12",
    "Location": "Tier 406",
    "Attribute": "Humanities and English:Lit Prior to 20th Cent and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 22367,
    "Subject": "ENGL",
    "Course": 2910,
    "Section": "A01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Comics",
    "Days": "TR",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 45,
    "Act": 45,
    "Rem": 0,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Lucas P. Tromly",
    "Date": "09/07-12/12",
    "Location": "401 Tier",
    "Attribute": "Humanities",
    "Labs": ""
  },
  {
    "CRN": 22368,
    "Subject": "ENGL",
    "Course": 3130,
    "Section": "T03",
    "Campus": "M",
    "Credits": 3,
    "Title": "Writing Romantic Women",
    "Days": "MWF",
    "Time": "11:30 AM - 12:20 PM",
    "Cap": 35,
    "Act": 32,
    "Rem": 3,
    "WLCap": 999,
    "WLAct": 0,
    "WLRem": 999,
    "Instructor": "Michelle M. Boyce",
    "Date": "09/07-12/12",
    "Location": "214 Tier",
    "Attribute": "Humanities and English:Lit Prior to 20th Cent and Written English Requirement",
    "Labs": ""
  },
  {
    "CRN": 22380,
    "Subject": "ENGL",
    "Course": 7050,
    "Section": "T02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Asian Canadian Cultural Activism",
    "Days": "M",
    "Time": "2:30 PM - 5:15 PM",
    "Cap": 11,
    "Act": 11,
    "Rem": 0,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Lindsay A. Diehl",
    "Date": "05/08-06/15",
    "Location": "304 Human Ecology",
    "Attribute": "N/A",
    "Labs": ""
  },
  {
    "CRN": 22380,
    "Subject": "ENGL",
    "Course": 7050,
    "Section": "T02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Asian Canadian Cultural Activism",
    "Days": "M",
    "Time": "2:30 PM - 5:15 PM",
    "Cap": 11,
    "Act": 6,
    "Rem": 5,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Lindsay A. Diehl",
    "Date": "09/07-12/12",
    "Location": "304 Human Ecology",
    "Attribute": "N/A",
    "Labs": ""
  },
  {
    "CRN": 53166,
    "Subject": "FMLY",
    "Course": 1000,
    "Section": "G01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Families in Contemporary Canadian Society",
    "Days": "TR",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 158,
    "Act": 137,
    "Rem": 21,
    "WLCap": 500,
    "WLAct": 0,
    "WLRem": 500,
    "Instructor": "Punam Mehta",
    "Date": "01/09-04/12",
    "Location": "100 Fletcher Argue",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 53166,
    "Subject": "FMLY",
    "Course": 1000,
    "Section": "G01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Families in Contemporary Canadian Society",
    "Days": "TR",
    "Time": "11:30 AM - 12:45 PM",
    "Cap": 158,
    "Act": 137,
    "Rem": 21,
    "WLCap": 500,
    "WLAct": 0,
    "WLRem": 500,
    "Instructor": "Punam Mehta",
    "Date": "09/07-12/12",
    "Location": "100 Fletcher Argue",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 53154,
    "Subject": "FMLY",
    "Course": 1010,
    "Section": "G01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human Development in the Family",
    "Days": "TR",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 240,
    "Act": 226,
    "Rem": 14,
    "WLCap": 200,
    "WLAct": 0,
    "WLRem": 200,
    "Instructor": "Tamara L. Taillieu",
    "Date": "01/09-04/12",
    "Location": "343 Drake Centre",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 53154,
    "Subject": "FMLY",
    "Course": 1010,
    "Section": "G01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human Development in the Family",
    "Days": "TR",
    "Time": "10:00 AM - 11:15 AM",
    "Cap": 240,
    "Act": 226,
    "Rem": 14,
    "WLCap": 200,
    "WLAct": 0,
    "WLRem": 200,
    "Instructor": "Tamara L. Taillieu",
    "Date": "09/07-12/12",
    "Location": "343 Drake Centre",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 53389,
    "Subject": "FMLY",
    "Course": 1010,
    "Section": "G02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human Development in the Family",
    "Days": "N/A",
    "Time": "N/A",
    "Cap": 225,
    "Act": 208,
    "Rem": 17,
    "WLCap": 225,
    "WLAct": 0,
    "WLRem": 225,
    "Instructor": "Punam Mehta",
    "Date": "01/09-04/12",
    "Location": "Distance And On-Line Education",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 61234,
    "Subject": "FMLY",
    "Course": 1010,
    "Section": "G02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human Development in the Family",
    "Days": "N/A",
    "Time": "N/A",
    "Cap": 225,
    "Act": 225,
    "Rem": 0,
    "WLCap": 225,
    "WLAct": 0,
    "WLRem": 225,
    "Instructor": "Punam Mehta",
    "Date": "05/08-06/15",
    "Location": "Distance And On-Line Education",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 53389,
    "Subject": "FMLY",
    "Course": 1010,
    "Section": "G02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Human Development in the Family",
    "Days": "N/A",
    "Time": "N/A",
    "Cap": 225,
    "Act": 225,
    "Rem": 0,
    "WLCap": 225,
    "WLAct": 225,
    "WLRem": 225,
    "Instructor": "Punam Mehta",
    "Date": "09/07-12/12",
    "Location": "Distance And On-Line Education",
    "Attribute": "Family Social Sciences and Recommended Intro Courses",
    "Labs": ""
  },
  {
    "CRN": 61696,
    "Subject": "FMLY",
    "Course": 2500,
    "Section": "G02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Diversity and Families",
    "Days": "M",
    "Time": "6:00 PM - 9:00 PM",
    "Cap": 75,
    "Act": 30,
    "Rem": 45,
    "WLCap": 100,
    "WLAct": 0,
    "WLRem": 100,
    "Instructor": "Ginelle R. Giacomin",
    "Date": "01/09-04/12",
    "Location": "350 Eitc E2",
    "Attribute": "Family Social Sciences",
    "Labs": ""
  },
  {
    "CRN": 61235,
    "Subject": "FMLY",
    "Course": 2500,
    "Section": "G02",
    "Campus": "M",
    "Credits": 3,
    "Title": "Diversity and Families",
    "Days": "M",
    "Time": "6:00 PM - 9:00 PM",
    "Cap": 75,
    "Act": 30,
    "Rem": 45,
    "WLCap": 100,
    "WLAct": 0,
    "WLRem": 100,
    "Instructor": "Ginelle R. Giacomin",
    "Date": "05/08-06/15",
    "Location": "350 Eitc E2",
    "Attribute": "Family Social Sciences",
    "Labs": ""
  },
  {
    "CRN": 62532,
    "Subject": "FMLY",
    "Course": 3240,
    "Section": "G01",
    "Campus": "M",
    "Credits": 3,
    "Title": "Families in Later Years",
    "Days": "M",
    "Time": "2:30 PM - 5:15 PM",
    "Cap": 50,
    "Act": 30,
    "Rem": 20,
    "WLCap": 0,
    "WLAct": 0,
    "WLRem": 0,
    "Instructor": "Barbara Borges",
    "Date": "01/09-04/12",
    "Location": "207 Human Ecology",
    "Attribute": "Agriculture: Option in Aging and Fac Health Sc: Option in Aging",
    "Labs": ""
  }
];

courseInformationList = [
  {
    "Course": "COMP 1010",
    "Description": "An introduction to computer programming using a procedural high level language.",
    "Prerequisites": "Any grade 12 or 40S Mathematics, or equivalent.",
    "Restrictions": "May not be held with COMP 1011 or COMP 1012 or COMP 1013."
  },
  {
    "Course": "COMP 1012",
    "Description": "An introduction to computer programming suitable for solving problems in science and engineering. Students will implement algorithms for numerical processing, statistical analysis and matrix operations.",
    "Prerequisites": "Mathematics 40S or equivalent. Co-requisite: MATH 1230 or MATH 1500 or MATH 1501 (or equivalent).",
    "Restrictions": "Not to be held with COMP 1010, COMP 1011 or COMP 1013."
  },
  {
    "Course": "COMP 1020",
    "Description": "More features of a procedural language, elements of programming.",
    "Prerequisites": "COMP 1010 or COMP 1011; or COMP 1012 or COMP 1013; or High School Computer Science 40S (75%) and any grade 12 or 40S Mathematics, or equivalent.",
    "Restrictions": "May not be held with COMP 1021."
  },
  {
    "Course": "COMP 2080",
    "Description": "Methods of analyzing the time and space requirements of algorithms. Average case and worst case analysis. Models of computation.",
    "Prerequisites": "MATH 1240, MATH 1241 or COMP 2130; and one of COMP 2140, or the former COMP 2061. STAT 1000 or STAT 1001 or STAT 1150 is strongly recommended.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 2140",
    "Description": "Introduction to the representation and manipulation of data structures. Topics will include lists, stacks, queues, trees, and graphs.",
    "Prerequisites": "One of COMP 1020, COMP 1021.",
    "Restrictions": "May not be held with COMP 2061."
  },
  {
    "Course": "COMP 2150",
    "Description": "An introduction to computer programming using a procedural high level language. ",
    "Prerequisites": "Any Grade 12 or 40S Mathematics, or equivalent.",
    "Restrictions": "May not be held with COMP 1011 or COMP 1012 or COMP 1013."
  },
  {
    "Course": "COMP 2160",
    "Description": "Introduction to issues involved in real-world computing. Topics will include memory management, debugging, compilation, performance, and good programming practices.",
    "Prerequisites": "COMP 1020 (C+) or COMP 1021 (C+).",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 2280",
    "Description": "Data representation and manipulation, machine-level representation of programs, assembly language programming, and basic computer architecture.",
    "Prerequisites": "COMP 2140, COMP 2160, and one of MATH 1240, MATH 1241 or COMP 2130.",
    "Restrictions": "Not available to students who have previously completed ECE 3610."
  },
  {
    "Course": "ENGL 0930",
    "Description": "Designed to help students write better essays. Course focuses on effective expression; sentence, paragraph, and essay construction; and the writing process. A great deal of writing is required; instructors address the particular needs of individual students.",
    "Prerequisites": "No prerequisites.",
    "Restrictions": "Students may not enter English courses numbered above the 1000 level directly from this course."
  },
  {
    "Course": "ENGL 1340",
    "Description": "This course is intended to provide students with reading, writing, and analytic skills required for literary studies.",
    "Prerequisites": "No prerequisites.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ENGL 2130",
    "Description": "A survey of poetry, prose and drama by major and minor writers in historical context.",
    "Prerequisites": "[ENGL 1200 or ENGL 1201 or ENGL 1300 or ENGL 1301] or [ENGL 1400 (or the former ENGL 1310) and ENGL 1340].",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ASTR 1810",
    "Description": "This introductory astronomy course surveys our magnificent Universe. The topics covered in this course outline the properties of stars and planets that can be observed and the physics necessary to interpret these observations. It also includes an introduction to galaxies and cosmology. Using lectures and laboratory sections, it provides an astronomy background and introduction to the scientific method. It ranges from introductory physical background to considering current research problems. This course is taught with algebra and trigonometry used frequently.",
    "Prerequisites": "(one of Physics 40S, PHYS 0900 (P), PSKL 0100 (P), PHYS 1018, or equivalent) and (one of Pre-calculus Mathematics 40S (70% or better), Applied Mathematics 40S (70% or better), MSKL 0100, MATH 1018, or equivalent).",
    "Restrictions": "May not be held with the former PHYS 1810."
  },
  {
    "Course": "FMLY 1000",
    "Description": "This course provides an introduction to issues in contemporary families from an interdisciplinary perspective. Changing and diverse family forms and experiences are reviewed. An overview of issues pertinent to family well-being, including but not limited to immigration, poverty, homelessness, racism, addiction, disability, divorce, and physical and mental illness is provided.",
    "Prerequisites": "No prerequisites.",
    "Restrictions": "Not to be held with FMLY 1020."
  },
  {
    "Course": "FMLY 1010",
    "Description": "Introductory survey of key aspects of human development processes within the family context from a life span perspective.",
    "Prerequisites": "No prerequisites.",
    "Restrictions": "Not to be held with NURS 1260."
  },
  {
    "Course": "FMLY 2500",
    "Description": "Using the theoretical frameworks of intersectionality and social ecology, this class addresses how diversity in Canada is influenced by age, gender, ability, ethnicity, race, as well as family relationships, institutions and social policies. A focus on human rights and anti-racism education is emphasized.",
    "Prerequisites": "FMLY 1000 (FMLY 1020) or FMLY 1010 or equivalent.",
    "Restrictions": "Not to be held with FMLY 2350."
  },
  {
    "Course": "FMLY 3240",
    "Description": "An investigation of family issues in the later years of life, such as housing, intergenerational relations, adjustment to retirement, sibling relations, grandparenting, death.",
    "Prerequisites": "[FMLY 1010 and FMLY 1000 (FMLY 1020)] or PSYC 1200 or SOC 1200.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 3020",
    "Description": "Human-computer interaction: human factors and usability, user-centered design, prototyping, usability evaluation.",
    "Prerequisites": "One of COMP 2140 or COMP 2061.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 3190",
    "Description": "Principles of artificial intelligence: problem solving, knowledge representation and manipulation; the application of these principles to the solution of 'hard' problems.",
    "Prerequisites": "One of COMP 2140 or COMP 2061.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 3370",
    "Description": "Principles of computer systems architecture, organization and design. Performance, instruction sets, processors, input/output, memory hierarchies.",
    "Prerequisites": "COMP 2280 or ECE 3610.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 3380",
    "Description": "An introduction to database systems including the relational, hierarchical, network and entity-relationship models with emphasis on the relational model and SQL.",
    "Prerequisites": "One of COMP 2140 or COMP 2061.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 3490",
    "Description": "An introductory course in computer graphics including topics such as raster graphics, two and three dimensional transforms, and simple rendering.",
    "Prerequisites": "COMP 2140; and either COMP 2190, or both: MATH 1300 (or MATH 1220, MATH 1310, MATH 1301, MATH 1210 or MATH 1211) and MATH 1500 (or MATH 1230, MATH 1501, MATH 1510 or MATH 1520).",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 4050",
    "Description": "Introduction to the issues involved in managing large, complex software projects.",
    "Prerequisites": "COMP 3350.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 4140",
    "Description": "Description and analysis of cryptographic methods used in the authentication and protection of data. Classical cryptosystems and cryptoanalysis, the Advanced Data Encryption Standard (ADES) and Publickey cryptosystems.",
    "Prerequisites": "One of COMP 3170, MATH 2170, or the former MATH 2500.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 4300",
    "Description": "This course examines the principles of computer networks, including network architectures, algorithms, protocols, and performance.",
    "Prerequisites": "COMP 2280 and COMP 3010.",
    "Restrictions": "May not be held with the former COMP 3720 or the former COMP 4720 or ECE 3700."
  },
  {
    "Course": "COMP 4360",
    "Description": "Learning strategies; evaluation of learning; learning in symbolic systems; neural networks, genetic algorithms.",
    "Prerequisites": "COMP 3190 or [STAT 2400, and MATH 2740, and DATA 2010].",
    "Restrictions": "May not be held with ECE 4450."
  },
  {
    "Course": "COMP 4510",
    "Description": "An overview of the architectures of current parallel processors and the techniques used to program them.",
    "Prerequisites": "COMP 3370 and COMP 3430.",
    "Restrictions": "Not to be held with ECE 4530."
  },
  {
    "Course": "COMP 7570",
    "Description": "Topics of current research interest in areas of computer science, available on an occasional basis, subject to the interests and availability of faculty.",
    "Prerequisites": "Written consent of instructor.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "COMP 7922",
    "Description": "The design and analysis of efficient algorithms for geometric problems. Possible topics include convex hull algorithms; Voronoi diagrams and Delaunay triangulations; point location; range searching; geometric data structures; geometric intersection algorithms; guarding and visibility graphs; geometric packing, covering, and partitioning; geometric duality; arrangements of lines and circles; unit disc graphs and proximity graphs.",
    "Prerequisites": "Written consent of instructor.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ASTR 2000",
    "Description": "This course covers the foundations of astrophysics, with emphasis on the core physical principles and processes that govern astronomical phenomena. The course emphasizes how the physics of matter, radiation, gravity, magnetic fields, and the interaction between light and matter can be used to understand a range of astrophysical phenomena, including fundamental processes, fascinating energetic objects, and topics at the forefront of modern research.",
    "Prerequisites": "(one of PHYS 1070, PHYS 1071, or PHYS 2152) or (a \"C+\" or better in PHYS 1030 or PHYS 1031) and (one of MATH 1232, MATH 1690, MATH 1700, MATH 1701, MATH 1710, or the former MATH 1730) or permission of the department.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ASTR 3070",
    "Description": "Students will learn to develop and execute an observational research project. Students will choose their research topic with the constraint that the data be collected using the University of Manitoba's Astronomical Observatory at Glenlea Astronomical Observatory and the Ewen Campus Telescopes. The optical observational data will be supplemented by archival data from professional research telescopes such as the Hubble Space Telescope, Chandra X-ray Observatory and others. The course covers the determination of observational constraints, the use of filters, methods of data analysis, and interpretation of results. The research project will be written into a report and presented.",
    "Prerequisites": "ASTR 2070 or the former PHYS 2070 or permission of the department.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ASTR 3180",
    "Description": "This course provides an overview of the physics of stars, including all phases of stellar evolution: from star formation, to the main-sequence phase, to star death, to the formation of degenerate or compact remnants such as white dwarfs, neutron stars and black holes. Topics include radiative transfer, stellar structure and atmosphere, nuclear fusion, stellar evolution, degenerate stars, and other exotic forms of compact stellar remnants.",
    "Prerequisites": "ASTR 2000 or permission of the department.",
    "Restrictions": "May not be held with the former PHYS 3180."
  },
  {
    "Course": "ENGL 2910",
    "Description": "An introduction to the analysis of comics and other graphic narrative forms.",
    "Prerequisites": "[one of ENGL 1200, ENGL 1201, ENGL 1300, or ENGL 1301] or [ENGL 1400 (the former ENGL 1310) and ENGL 1340].",
    "Restrictions": "May not be held with ENGL 3800 when titled “Panels and Frame.”"
  },
  {
    "Course": "ENGL 3130",
    "Description": "The content of this course will vary from year to year. Students are asked to consult the Department of English, Theatre, Film & Media website for detailed course descriptions. The course content may vary. Students can earn multiple credits for this course only when the topic subtitle is different.",
    "Prerequisites": "Six hours of English at the 2000 level.",
    "Restrictions": "No restrictions."
  },
  {
    "Course": "ENGL 7050",
    "Description": "A detailed study of an aspect of Canadian Literature. Topics will vary from year to year. The course content may vary. Students can earn multiple credits for this course only when the topic subtitle is different.",
    "Prerequisites": "No prerequisites.",
    "Restrictions": "Not to be held with the former ENGL 7040."
  }
];